version: '3.8'
services:
  frontend:
    container_name: 'project-frontend'
    image: 'arkarmintun/project-frontend'
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./client:/usr/src/app

  backend:
    container_name: 'project-backend'
    image: 'arkarmintun/project-backend'
    env_file: ./.env
    environment:
      MONGO_USER: $DB_USERNAME
      MONGO_PASS: $DB_PASSWORD
      MONGO_HOST: $DB_HOST
      MONGO_PORT: $DB_PORT
      MONGO_NAME: $DB_NAME
      NODE_ENV: $NODE_ENV
      SERVER_PORT: $SERVER_PORT
      JWT_SECRET: $JWT_SECRET

    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - database

  database:
    container_name: 'project-database'
    image: mongo
    env_file: ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
